spring:
  datasource:
    url: jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
    username: ${PGUSER}
    password: ${PGPASSWORD}
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    open-in-view: false
  jackson:
    serialization:
      indent_output: ${JSON_PRETTY_PRINT:true}
