openapi: "3.0.3"
info:
  title: "Poll api"
  version: "1.0"
paths:
  /subjects/{subjectId}/polls:
    get:
      tags:
        - Polls
      summary: Gets all polls
      operationId: getPolls
      parameters:
        - name: subjectId
          in: path
          required: true
          schema:
            $ref: "./subject-definitions.yaml#/components/schemas/SubjectId"
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "./poll-definitions.yaml#/components/schemas/PollResponse"
    post:
      tags:
        - Polls
      summary: Adds poll
      operationId: addPoll
      parameters:
        - name: subjectId
          in: path
          required: true
          schema:
            $ref: "./subject-definitions.yaml#/components/schemas/SubjectId"
      requestBody:
        description: Poll to be added
        required: true
        content:
          application/json:
            schema:
              $ref: "./poll-definitions.yaml#/components/schemas/PollCreate"
      responses:
        "201":
          description: Poll created
          content:
            application/json:
              schema:
                $ref: "./poll-definitions.yaml#/components/schemas/PollResponse"
          headers:
            Location:
              description: Location of newly created poll
              schema:
                type: string
        "400":
          description: Wrong format
        "409":
          description: Poll already exists
          headers:
            Location:
              description: Location of existing poll
              schema:
                type: string
    put:
      tags:
        - Polls
      summary: Updates poll
      operationId: updatePoll
      parameters:
        - name: subjectId
          in: path
          required: true
          schema:
            $ref: "./subject-definitions.yaml#/components/schemas/SubjectId"
      requestBody:
        description: Poll to be updated
        required: true
        content:
          application/json:
            schema:
              $ref: "./poll-definitions.yaml#/components/schemas/PollUpdate"
      responses:
        "200":
          description: Poll updated
          content:
            application/json:
              schema:
                $ref: "./poll-definitions.yaml#/components/schemas/PollResponse"
        "400":
          description: Wrong format
        "404":
          description: Poll not found
  /subjects/{subjectId}/polls/{pollId}:
    get:
      tags:
        - Polls
      summary: Gets poll by id
      operationId: getPollById
      parameters:
        - name: subjectId
          in: path
          required: true
          schema:
            $ref: "./subject-definitions.yaml#/components/schemas/SubjectId"
        - name: pollId
          in: path
          required: true
          schema:
            $ref: "./poll-definitions.yaml#/components/schemas/PollId"
      responses:
        "200":
          description: Poll found
          content:
            application/json:
              schema:
                $ref: "./poll-definitions.yaml#/components/schemas/PollResponse"
        "404":
          description: Poll not found
    delete:
      tags:
        - Polls
      summary: Deletes poll by id
      operationId: deletePollById
      parameters:
        - name: subjectId
          in: path
          required: true
          schema:
            $ref: "./subject-definitions.yaml#/components/schemas/SubjectId"
        - name: pollId
          in: path
          required: true
          schema:
            $ref: "./poll-definitions.yaml#/components/schemas/PollId"
      responses:
        "204":
          description: Poll deleted
        "404":
          description: Poll not found


