openapi: "3.0.3"
info:
  title: "Poll definitions"
  version: "1.0"
paths: {}
components:
  schemas:
    PollCreate:
      type: object
      required:
        - name
        - endDate
      properties:
        name:
          $ref: '#/components/schemas/PollName'
        endDate:
          $ref: '#/components/schemas/PollEndDate'
    PollUpdate:
      type: object
      required:
        - id
      properties:
        id:
          $ref: '#/components/schemas/PollId'
        name:
          $ref: '#/components/schemas/PollName'
        endDate:
          $ref: '#/components/schemas/PollEndDate'
    PollResponse:
      type: object
      required:
        - id
        - name
        - endDate
      properties:
        id:
          $ref: '#/components/schemas/PollId'
        name:
          $ref: '#/components/schemas/PollName'
        endDate:
          $ref: '#/components/schemas/PollEndDate'
    PollId:
      type: integer
      format: int64
      minimum: 0
    PollName:
      type: string
      maxLength: 200
    PollEndDate:
      type: string
      format: date-time
      minimum: 0
    Error:
      type: object
      properties:
        error:
          type: string
          maxLength: 200

