openapi: "3.0.3"
info:
  title: "Subject definitions"
  version: "1.0"
paths: {}
components:
  schemas:
    Subject:
      type: object
      required:
        - id
      properties:
        id:
          $ref: '#/components/schemas/SubjectId'
        name:
          $ref: '#/components/schemas/SubjectName'
    SubjectId:
      type: integer
      format: int64
      minimum: 0
    SubjectName:
      type: string
      maxLength: 200
    Error:
      type: string
      maxLength: 200

