openapi: "3.0.3"
info:
  title: "Subject definitions"
  version: "1.0"
paths: {}
components:
  schemas:
    Subject:
      type: object
      required:
        - id
      properties:
        id:
          type: integer
          format: int64
          minimum: 0
        name:
          type: string
          maxLength: 200

